fix(app): eslint errors

diff --git a/.github/workflows/supabase-keepalive.yml b/.github/workflows/supabase-keepalive.yml
--- a/.github/workflows/supabase-keepalive.yml
+++ b/.github/workflows/supabase-keepalive.yml
@@ -11,16 +11,16 @@ jobs:
     steps:
       - name: Insert cron job with message
         run: |
-            DATE_STR=$(date -u +"%A, %d %B, %Y")
-            MESSAGE="Cron job created on $DATE_STR"
-            response=$(curl -s -w "%{http_code}" -X POST ${{ secrets.SUPABASE_URL }}/rest/v1/app_cron_jobs \
-            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
-            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
-            -H "Content-Type: application/json" \
-            -d "{\"message\": \"$MESSAGE\"}")
+          DATE_STR=$(date -u +"%A, %d %B, %Y")
+          MESSAGE="Cron job created on $DATE_STR"
+          response=$(curl -s -w "%{http_code}" -X POST ${{ secrets.SUPABASE_URL }}/rest/v1/app_cron_jobs \
+          -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
+          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
+          -H "Content-Type: application/json" \
+          -d "{\"message\": \"$MESSAGE\"}")
 
-            http_code="${response: -3}"
-            if [ "$http_code" -ne 201 ] && [ "$http_code" -ne 200 ]; then
-            echo "Failed to insert cron job. HTTP code: $http_code"
-            exit 1
-            fi
+          http_code="${response: -3}"
+          if [ "$http_code" -ne 201 ] && [ "$http_code" -ne 200 ]; then
+          echo "Failed to insert cron job. HTTP code: $http_code"
+          exit 1
+          fi
